### ISSUE TITLE
Missing model grapefruitv4

### ISSUE THREAD

**Issue by AlRez2400** [Meldoner/stable-diffusion-webui-colab#3]
please add module "grapefruitv4", How can you quickly add.

**Comment by Meldoner** [comment]
@AlRez2400  hassaku is grapefruit

**Comment by AlRez2400** [comment]
so will you add? I am good at creating pictures with this module

**Comment by AlRez2400** [comment]
and thank you for what you did. My PC can't handle the load on the video card. 😓

**Comment by Meldoner** [comment]
I mean grapefruit is already there, it's just called Hassaku, it's a new version of grapefruit

**Comment by AlRez2400** [comment]
dude, I already thought that you removed from the list. thanks for saying

**Comment by AlRez2400** [comment]
upload your model, how is it? from the Internet or from your disk?

**Comment by Meldoner** [comment]
> upload your model, how is it? from the Internet or from your disk?

from huggingface

**Comment by AlRez2400** [comment]
"Click if you want to upload your model", how? from the Internet or from your disk?

**Comment by Meldoner** [comment]
> "Click if you want to upload your model", how? from the Internet or from your disk?

from internet, huggingface.co

**Comment by AlRez2400** [comment]
I have so many questions and so few answers. what module would you recommend me to use?

**Comment by AlRez2400** [comment]
Are there other sites besides this?
