### ISSUE TITLE
вы где

### ISSUE THREAD

**Issue by AlRez2400** [Meldoner/stable-diffusion-webui-colab#8]
ми по вас скучаем😭

**Comment by Meldoner** [comment]
К сожалению Stable Diffusion больше нельзя использовать в бесплатной версии Google Colab

**Comment by AlRez2400** [comment]
можно только использовать в платном версии? и как?

**Comment by Meldoner** [comment]
> можно только использовать в платном версии? и как?

Google Colab запретили использовать их бесплатный сервис для SD, только с платной подпиской
